### ISSUE TITLE
Maybe it wouldn't be a terrible idea to add a version command?

### ISSUE THREAD

**Issue by Saltystew** [MediaButler/MediaButler#113]

**Comment by vertig0ne** [comment]
At the moment there is a bit of confusion with the versioning scheme, the best way you can tell right now is ia via the "Playing MediaButler v0.0" on Discord, this is pushed with every set of major updates. Due to the fact we are still settling on our feet it is kind of difficult to apply a version scheme. You can find out exactly which commit you are running by checking the .git folder inside the MediaButler folder, inside there you will see a file called FETCH_HEAD.

    983b1f21afbfda0b9bc319f95888c40ec00fd6ed		branch 'master' of https://github.com/vertig0ne/MediaButler
    767bb6bb291d0ff26d22fc4c57660692d2243bf9	not-for-merge	branch 'public-bot' of https://github.com/vertig0ne/MediaButler

As you can see there, it tells me I am currently on commit 983b1f21afbfda0b9bc319f95888c40ec00fd6ed which if you look at my fork of MediaButler is currently (at the time of writing this) the latest version on my fork.
