### ISSUE TITLE
Use plexpy friendly name instead of userid for plexpy history or stats command?

### ISSUE THREAD

**Issue by Saltystew** [MediaButler/MediaButler#86]
A lot of my users userid is the beginning of their email or something, and I don't remember it at all so for plexpy I just renamed them all with their first name using the friendly name option.

Maybe this could be added as an option for those two commands?

**Comment by vertig0ne** [comment]
The userId requirement is because of PlexPy, the commands work by making 2 calls to PlexPy, one to actually get the userId of the username you provide and the 2nd is the actual thing you want.

My advice at this stage would be to use the "User" field on PlexPy for the input, it is VERY case-sensitive. We have been looking at other options to make it "better' but, hitting walls at the moment.
